//attribute : glacio(응결), fusion(용융), conducto(전도), aero(기류), spectra(회절), havoc(인멸)
//weapon : greatsword(대검), straightsword(직검), gun(권총), fist(권갑), amplifier(증폭기)

//캐릭터
const characters = [
		{ "name": "sanhua", "star": 4, "attribute": "glacio", "weapon" : "straightsword", "img": "images/resonator/sanhua.jpg",
		  "grow item": "", "skill bonus1" : "atk", "skill bonus2" : "glacio dmg",
		  "KR_name" : "산화"},
		{ "name": "phoebe", "star": 5, "attribute": "spectra", "weapon" : "amplifier", "img": "images/resonator/phoebe.jpg",
		  "KR_name" : "페비"},
		{ "name": "cartethyia", "star": 5, "attribute": "aero", "weapon" : "straightsword", "img": "images/resonator/cartethyia.jpg",
		  "KR_name" : "카르티시아"},
		{ "name": "augusta", "star": 5, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/augusta.jpg",
		  "KR_name" : "아우구스타"},
		{ "name": "carlotta", "star": 5, "attribute": "glacio", "weapon" : "gun", "img": "images/resonator/carlotta.jpg",
		  "KR_name" : "카를로타"},
		{ "name": "galbrena", "star": 5, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/galbrena.jpg",
		  "KR_name" : "갈브레나"},
		{ "name": "phrolova", "star": 5, "attribute": "havoc", "weapon" : "amplifier", "img": "images/resonator/phrolova.jpg",
		  "KR_name" : "플로로"},
		{ "name": "iuno", "star": 5, "attribute": "aero", "weapon" : "fist", "img": "images/resonator/iuno.jpg",
		  "KR_name" : "유노"},
		{ "name": "baizhi", "star": 4, "attribute": "glacio", "weapon" : "amplifier", "img": "images/resonator/baizhi.jpg",
		  "KR_name" : "설지"},
		{ "name": "brant", "star": 5, "attribute": "fusion", "weapon" : "straightsword", "img": "images/resonator/brant.jpg",
		  "KR_name" : "브렌트"},
		{ "name": "calcharo", "star": 5, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/calcharo.jpg",
		  "KR_name" : "카카루"},
		{ "name": "changli", "star": 5, "attribute": "fusion", "weapon" : "straightsword", "img": "images/resonator/changli.jpg",
		  "KR_name" : "장리"},
		{ "name": "chixia", "star": 4, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/chixia.jpg",
		  "KR_name" : "치샤"},
		{ "name": "encore", "star": 5, "attribute": "fusion", "weapon" : "fist", "img": "images/resonator/encore.jpg",
		  "KR_name" : "앙코"},
		{ "name": "lingyang", "star": 5, "attribute": "glacio", "weapon" : "fist", "img": "images/resonator/lingyang.jpg",
		  "KR_name" : "능양"},
		{ "name": "lumi", "star": 4, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/lumi.jpg",
		  "KR_name" : "루미"},
		{ "name": "lupa", "star": 5, "attribute": "fusion", "weapon" : "greatsword", "img": "images/resonator/lupa.jpg",
		  "KR_name" : "루파"},
		{ "name": "mortefi", "star": 4, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/mortefi.jpg",
		  "KR_name" : "모르테피"},
		{ "name": "xiangliYao", "star": 5, "attribute": "conducto", "weapon" : "fist", "img": "images/resonator/xiangliYao.jpg",
		  "KR_name" : "상리요"},
		{ "name": "yinlin", "star": 5, "attribute": "conducto", "weapon" : "amplifier", "img": "images/resonator/yinlin.jpg",
		  "KR_name" : "음림"},
		{ "name": "youhu", "star": 4, "attribute": "glacio", "weapon" : "fist", "img": "images/resonator/youhu.jpg",
		  "KR_name" : "유호"},
		{ "name": "yuanwu", "star": 5, "attribute": "conducto", "weapon" : "fist", "img": "images/resonator/yuanwu.jpg",
		  "KR_name" : "연무"},
		{ "name": "zhezhi", "star": 5, "attribute": "glacio", "weapon" : "amplifier", "img": "images/resonator/zhezhi.jpg",
		  "KR_name" : "절지"},
		{ "name": "sanhua", "star": 4, "attribute": "glacio", "weapon" : "straightsword", "img": "images/resonator/sanhua.jpg",
		  "grow item": "", "skill bonus1" : "atk", "skill bonus2" : "glacio dmg",
		  "KR_name" : "산화"},
		{ "name": "phoebe", "star": 5, "attribute": "spectra", "weapon" : "amplifier", "img": "images/resonator/phoebe.jpg",
		  "KR_name" : "페비"},
		{ "name": "cartethyia", "star": 5, "attribute": "aero", "weapon" : "straightsword", "img": "images/resonator/cartethyia.jpg",
		  "KR_name" : "카르티시아"},
		{ "name": "augusta", "star": 5, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/augusta.jpg",
		  "KR_name" : "아우구스타"},
		{ "name": "carlotta", "star": 5, "attribute": "glacio", "weapon" : "gun", "img": "images/resonator/carlotta.jpg",
		  "KR_name" : "카를로타"},
		{ "name": "galbrena", "star": 5, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/galbrena.jpg",
		  "KR_name" : "갈브레나"},
		{ "name": "phrolova", "star": 5, "attribute": "havoc", "weapon" : "amplifier", "img": "images/resonator/phrolova.jpg",
		  "KR_name" : "플로로"},
		{ "name": "iuno", "star": 5, "attribute": "aero", "weapon" : "fist", "img": "images/resonator/iuno.jpg",
		  "KR_name" : "유노"},
		{ "name": "baizhi", "star": 4, "attribute": "glacio", "weapon" : "amplifier", "img": "images/resonator/baizhi.jpg",
		  "KR_name" : "설지"},
		{ "name": "brant", "star": 5, "attribute": "fusion", "weapon" : "straightsword", "img": "images/resonator/brant.jpg",
		  "KR_name" : "브렌트"},
		{ "name": "calcharo", "star": 5, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/calcharo.jpg",
		  "KR_name" : "카카루"},
		{ "name": "changli", "star": 5, "attribute": "fusion", "weapon" : "straightsword", "img": "images/resonator/changli.jpg",
		  "KR_name" : "장리"},
		{ "name": "chixia", "star": 4, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/chixia.jpg",
		  "KR_name" : "치샤"},
		{ "name": "encore", "star": 5, "attribute": "fusion", "weapon" : "fist", "img": "images/resonator/encore.jpg",
		  "KR_name" : "앙코"},
		{ "name": "lingyang", "star": 5, "attribute": "glacio", "weapon" : "fist", "img": "images/resonator/lingyang.jpg",
		  "KR_name" : "능양"},
		{ "name": "lumi", "star": 4, "attribute": "conducto", "weapon" : "greatsword", "img": "images/resonator/lumi.jpg",
		  "KR_name" : "루미"},
		{ "name": "lupa", "star": 5, "attribute": "fusion", "weapon" : "greatsword", "img": "images/resonator/lupa.jpg",
		  "KR_name" : "루파"},
		{ "name": "mortefi", "star": 4, "attribute": "fusion", "weapon" : "gun", "img": "images/resonator/mortefi.jpg",
		  "KR_name" : "모르테피"},
		{ "name": "xiangliYao", "star": 5, "attribute": "conducto", "weapon" : "fist", "img": "images/resonator/xiangliYao.jpg",
		  "KR_name" : "상리요"},
		{ "name": "yinlin", "star": 5, "attribute": "conducto", "weapon" : "amplifier", "img": "images/resonator/yinlin.jpg",
		  "KR_name" : "음림"},
		{ "name": "youhu", "star": 4, "attribute": "glacio", "weapon" : "fist", "img": "images/resonator/youhu.jpg",
		  "KR_name" : "유호"},
		{ "name": "yuanwu", "star": 5, "attribute": "conducto", "weapon" : "fist", "img": "images/resonator/yuanwu.jpg",
		  "KR_name" : "연무"},
		{ "name": "zhezhi", "star": 5, "attribute": "glacio", "weapon" : "amplifier", "img": "images/resonator/zhezhi.jpg",
		  "KR_name" : "절지"},
	];
	
//무기
const weapons = [
		{ "name": "천년의 회류", "star": 5, "weapon" : "straightsword", "img" : "images/weapon/천년의 회류.jpg"},
		{ "name": "견습용 권총", "star": 1, "weapon" : "gun", "img" : "images/weapon/견습용 권총.jpg"},
		{ "name": "수호자의 권총 · 용맹", "star": 3, "weapon" : "gun", "img" : "images/weapon/수호자의 권총 · 용맹.jpg"},
		{ "name": "천년의 회류", "star": 5, "weapon" : "straightsword", "img" : "images/weapon/천년의 회류.jpg"},
		{ "name": "견습용 권총", "star": 1, "weapon" : "gun", "img" : "images/weapon/견습용 권총.jpg"},
		{ "name": "수호자의 권총 · 용맹", "star": 3, "weapon" : "gun", "img" : "images/weapon/수호자의 권총 · 용맹.jpg"},
		{ "name": "천년의 회류", "star": 5, "weapon" : "straightsword", "img" : "images/weapon/천년의 회류.jpg"},
		{ "name": "견습용 권총", "star": 1, "weapon" : "gun", "img" : "images/weapon/견습용 권총.jpg"},
		{ "name": "수호자의 권총 · 용맹", "star": 3, "weapon" : "gun", "img" : "images/weapon/수호자의 권총 · 용맹.jpg"},
	];